name: Delete Sandbox after Merge

on:
  pull_request:
    branches: [main, develop]
    types: [closed]

jobs:
  delete-sandbox:
    timeout-minutes: 60
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      DOTENV_ENV: ci
      SANDBOX_NAME: ci-pr-${{ github.event.pull_request.number }}
    permissions:
      contents: read
      id-token: write # oidc用
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # setup env
      - name: Setup environment file
        run: |
          printf "%s" "${{ secrets.CI_ENV_FILE }}" > .env.ci

      # configure aws credentials
      - name: Configure AWS Credentials（GitHub Actions）
        if: ${{ !env.ACT }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: githubActionsForPlaywright

      - name: Configure AWS Credentials（Act）
        if: ${{ env.ACT }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Corepack enable
        run: corepack enable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Delete Sandbox
        run: |
          echo "Deleting sandbox for branch: $SANDBOX_NAME"
          pnpm sandbox:delete --identifier $SANDBOX_NAME -y

      - name: Delete Sandbox Secret
        run: |
          echo "Deleting sandbox secret for branch: $SANDBOX_NAME"
          pnpm sandbox:delete_secret --identifier $SANDBOX_NAME GOOGLE_CLIENT_ID
          pnpm sandbox:delete_secret --identifier $SANDBOX_NAME GOOGLE_CLIENT_SECRET
